# Generated by Django 3.0.3 on 2020-03-08 07:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chartofaccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('account_detailtype', models.CharField(max_length=100)),
                ('account_description', models.CharField(max_length=250)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='companyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=100)),
                ('company_fax', models.CharField(max_length=100)),
                ('company_country', models.CharField(max_length=100)),
                ('company_city', models.CharField(max_length=100)),
                ('company_state', models.CharField(max_length=100)),
                ('company_zip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_city', models.CharField(max_length=100)),
                ('employee_status', models.CharField(max_length=20)),
                ('employee_position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='journalmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreate', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='service_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='serviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_sku', models.CharField(max_length=100)),
                ('service_description', models.CharField(max_length=100)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_category', to='massage.service_category')),
                ('service_income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_account', to='massage.chartofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('newbalance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('account_involved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_account', to='massage.chartofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='journalcollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Date')),
                ('debits', models.DecimalField(decimal_places=2, max_digits=6)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=200)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_account', to='massage.chartofaccounts')),
                ('journalid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='massage.journalmain')),
            ],
        ),
    ]
