# Generated by Django 3.0.3 on 2020-03-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalmain',
            old_name='datecreate',
            new_name='datecreated',
        ),
    ]
