# Generated by Django 3.0.3 on 2020-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.CharField(choices=[('Current assets', 'Current assets'), ('Non-current assets', 'Non-current assets'), ('Current liabilities', 'Current liabilities'), ('Non-current liabilities', 'Non-current liabilities'), ("Owner's equity", "Owner's equity"), ('Expenses', 'Expenses'), ('Income', 'Income')], max_length=100),
        ),
        migrations.DeleteModel(
            name='journalTotals',
        ),
    ]
