# Generated by Django 3.0.3 on 2020-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_auto_20200310_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='account_number',
            field=models.IntegerField(default=110, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
