# Generated by Django 3.0.3 on 2020-03-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0003_auto_20200310_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='account_description',
        ),
    ]
