# Generated by Django 3.0.3 on 2020-03-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0005_auto_20200310_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_balance',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journalcollections',
            name='credits',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journalcollections',
            name='debits',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='logs',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='logs',
            name='newbalance',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='service_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
