# Generated by Django 3.0.3 on 2020-03-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0006_auto_20200311_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartofaccounts',
            old_name='account_balance',
            new_name='account_credbalance',
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='account_debbalance',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
