# Generated by Django 3.0.3 on 2020-03-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0007_auto_20200311_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalTotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(unique=True)),
                ('account_debbalance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('account_credbalance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='totals_account', to='massage.chartofaccounts')),
                ('journalid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journalsmain', to='massage.journalmain')),
            ],
        ),
    ]
