# Generated by Django 3.0.3 on 2020-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0008_journaltotals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltotals',
            name='account_number',
            field=models.IntegerField(),
        ),
    ]
